Marketplace contract implementation
swanky-dapps/marketplace pull request #4
Opened 2023-01-02 07:49 UTC by bobo-k2

This is PR for initial implementation of the NFT marketplace contract with the following features:
- `factory` - creates a new instance of Shiden34 contract and registers the instance to the Marketplace. Caller needs to provide link to IPFS metadata file for NFT and some NFT details. Prerequisite for the factory is that Shiden34 contract is deployed to a network and the contract hash is provided to the Marketplace via `set_nft_contract_hash` call.
- `register` - registers an existing contract to the Marketplace.  This operation can be performed by contract or marketplace owner.
- `list` - Lists a NFT for sale on the marketplace. This operation can be performed by a token owner.
- `unlist` - Un-lists a NFT from the marketplace. This operation can be performed by a token owner.
- `buy` - Transfers a token ownership to the caller. Also pays royalties and marketplace fees predefined receivers.

2023-01-03 11:02 UTC, PierreOssun commented on contracts/marketplace/Cargo.toml
> +# getrandom = { version = "0.2", features = ["js"] }
delete if unused

2023-01-03 11:02 UTC, PierreOssun commented on contracts/psp34/lib.rs
> +            ink_lang::codegen::initialize_contract(|_instance: &mut Contract| {
no need underscore `_instance` as it is used

2023-01-03 11:02 UTC, PierreOssun commented on contracts/psp34/lib.rs
> +                    .expect("Can mint");
```suggestion
                    .expect("Can't mint");
```

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        let nonce = self.data::<Data>().nonce + 1;
This can overflow

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +                .unwrap();
Should not panic! here. You should return collection not found Error

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +                .checked_div(10_000)
checked_div ensures it doesn't divide by zero. As here you divide by a non zero const, using this function is useless. You can use `/`.
Ps same for others checked_div(10_000)

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +                if PSP34Ref::transfer(
Idiomatic Rust uses match pattern for this kind of expression checks
```
match transfer {
        Ok(_) => {...},
        Err(e) => return Err(e),
    };
```

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +                return Err(MarketplaceError::NotOwner)
`if let Some(v) => ..` pattern should only be used if the `None` is not handled.
It is a shorthand of 
```
match option {
Some(v) => ..
None => ..
}
```
Sending err is else statement is anti pattern (and here not really readable as you need to understand brackets alignment to know what it refers to).
Best option is to unwrap the value and send error if None in one instruction:
```
let item = self
            .data::<Data>()
            .items
            .get(&(contract_address, token_id.clone()))
            .ok_or(Err)?
```
So checks of `NotOwner` and `ItemNotListedForSale` should be refactored.

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        if self
use match pattern here

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        if let Some(item) = self.data::<Data>().items.get(&(contract_address, token_id)) {
if let is useless here.
Just `return self.data::<Data>().items.get(&(contract_address, token_id))` as it returns Option already

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        if let Some(collection) = self
either match pattern or get collection with o_or() to return erro if None and update it afterhand.

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        if let Some(token_owner) = PSP34Ref::owner_of(&contract_address, token_id.clone()) {
match pattern

2023-01-03 11:02 UTC, PierreOssun commented on logics/impls/marketplace/types.rs
> +    ContractAlreadyRegistered,
Add description =)

2023-01-03 11:02 UTC, PierreOssun commented on contracts/psp34/lib.rs
> +    pub struct Contract {
better rename the struct  Psp34Contract

2023-01-03 14:29 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +            .ok_or(MarketplaceError::CanNotDetermineOwner)?;
I think if token has no owner that's means it doesn't exit.
[link](https://github.com/Supercolony-net/openbrush-contracts/blob/e366f6ff1e5892c6a624833dd337a6da16a06baa/contracts/src/token/psp34/psp34.rs#L183)
I will return `TokenDoesNotExist` instead.

2023-01-03 14:29 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +            _ => return Err(MarketplaceError::UnableToTransferToken),
PSP34Ref::transfer returns a Result<T, E> whivh is an enum with two variant: Ok & Err
So here handle `Err` case and not `_`
Also you can add return before `match PSP34Ref::transfer(`
and remove it in the match branchs

2023-01-03 14:29 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        match PSP34Ref::owner_of(&contract_address, token_id.clone()) {
```
        match PSP34Ref::owner_of(&contract_address, token_id.clone()) {
            Some(token_owner) => {
                if caller != token_owner {
                    return Err(MarketplaceError::NotOwner);
                }
                Ok(())
            }
            None => Err(MarketplaceError::CanNotDetermineOwner),
        }
```

2023-01-03 14:29 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        match PSP34Ref::owner_of(&contract_address, token_id.clone()) {
you can remove the clone `token_id.clone()`

2023-01-04 07:57 UTC, PierreOssun reviewed
You should run `cargo clippy` and checks the hints to make your code mode clean/idiomatic

2023-01-04 07:57 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +            None => return Err(MarketplaceError::TokenDoesNotExist),
you can remove this `return`

2023-01-04 07:57 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +            Err(_e) => return Err(MarketplaceError::UnableToTransferToken),
just leave `_` and you can omit this `return`

2023-01-04 07:57 UTC, PierreOssun commented on logics/impls/marketplace/marketplace_sale.rs
> +        return match PSP34Ref::owner_of(&contract_address, token_id) {
This `return` can be removed as well

2023-01-04 10:23 UTC, PierreOssun approved these changes
LGTM

2023-01-05 05:05 UTC, 123oli commented
Is [contract_hash](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L85) in [factory](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L74) same as [contract_address](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L232) in [register's](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L230) Marketplace contract implementation? I mean are they both `Shiden34` contract hash?

2023-01-05 05:12 UTC, 123oli commented
[while fee calculating](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L198) why divide with `10_000`?

2023-01-05 08:01 UTC, bobo-k2 commented
> Is [contract_hash](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L85) in [factory](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L74) same as [contract_address](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L232) in [register's](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L230) Marketplace contract implementation? I mean are they both `Shiden34` contract hash?

Those two are not the same, the first one is contact hash, the second one is the deployed contract instance address.
Factory method will create a new instance of Shiden34 contract based on a hash of a contract already deployed on a network. Which means you can create your own NFT just by providing metadata.
Via register method you can register already instantiated Shiden34 contract by providing the contract address. Let's say you already deployed your contract and created NFTs and just want to register it to the marketplace.

2023-01-05 09:09 UTC, bobo-k2 commented
> [while fee calculating](https://github.com/swanky-dapps/marketplace/blob/56b4273a4e6673f282fb72c9e0ac274e931b9991/logics/impls/marketplace/marketplace_sale.rs#L198) why divide by `10_000`?

fee is percentage represented by integer value 100 is 1%, while 10_000 is 100%. If we want to calculate 10% fee we need to do the following 1_000 / 10_000

2023-01-05 10:26 UTC, Maar-io commented on contracts/marketplace/lib.rs
> +        // }
#[ink::test]
        fn factory_fails_if_no_hash() {
            let mut marketplace = init_contract();
            let accounts = default_accounts();

            assert_eq!(
                marketplace.factory(        
                    String::from("ipfs"),
                    accounts.alice,
                    100,
                    String::from("name"),
                    String::from("symbol"),
                    String::from("base_uri"),
                    0,
                    0,
                ),
                Err(MarketplaceError::NftContractHashNotSet)
            );
        }

2023-01-05 10:33 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +                }
you can use `ensure!` here

2023-01-05 10:37 UTC, Maar-io commented
Add comment for each function in traits and impl

2023-01-05 11:10 UTC, bobo-k2 commented
> Add comment for each function in traits and impl

Why to have the same comments on both places? This will be hard to maintain.

2023-01-09 08:54 UTC, Maar-io requested changes

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +        self.data::<Data>().items.insert(
perhaps adding check if Item is already listed. Might be FE issue if price is changed without unlisting first

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +
What if unlisting not listed item?

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +        ensure!(token_owner != caller, MarketplaceError::AlreadyOwner);
move upwards, before the calculations

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +        }
buy function is long. Perhaps this transfer section is good candidate to be moved as sub-function returning the Result

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +    default fn get_contract(&self, contract_address: AccountId) -> Option<RegisteredCollection> {
better to call function `get_registered_collection()`

2023-01-09 08:54 UTC, Maar-io commented on logics/impls/marketplace/marketplace_sale.rs
> +    default fn check_owner(
since there are 3 kinds of owners (marketplace, contract, token) it would be good to name this as `check_token_owner()`

2023-01-09 20:06 UTC, Maar-io commented on logics/traits/marketplace.rs
> +    /// Removes aa NFT from the marketplace sale.
aa

2023-01-09 20:07 UTC, Maar-io approved these changes
LGTM

2023-01-12 12:47 UTC, merged